


version: '3.8'

services:
  django:
    build:
      context: .
    container_name: django-app-test
    ports:
      - "8000:8000"
    environment:
      DJANGO_SETTINGS_MODULE: auth.settings  # Replace 'auth.settings' with your settings module
      DATABASE_HOST: db
      DATABASE_PORT: 3306
      MYSQL_DATABASE: django_db
      MYSQL_USER: test
      MYSQL_PASSWORD: test
      MYSQL_ROOT_PASSWORD: test
    volumes:
      - .:/app
      - static_volume:/app/static
    depends_on:
      - db

  db:
    image: mysql:8.0
    container_name: mysql-db
    restart: always
    environment:
      MYSQL_DATABASE: django_db
      MYSQL_USER: test
      MYSQL_PASSWORD: test
      MYSQL_ROOT_PASSWORD: test
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
  static_volume:





