# Generated by Django 5.0.7 on 2024-11-02 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Image', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='generatedimage',
            name='image_url',
        ),
        migrations.AddField(
            model_name='generatedimage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='generated_images/'),
        ),
    ]
