# Generated by Django 5.0.7 on 2024-11-06 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Image', '0002_remove_generatedimage_image_url_generatedimage_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='generatedimage',
            name='likes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='generatedimage',
            name='visibility',
            field=models.BooleanField(default=False),
        ),
    ]
