# Generated by Django 5.0.7 on 2024-11-06 02:51

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Image', '0004_remove_generatedimage_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='generatedimage',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
