from django.db import models
from django.conf import settings

class Video(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.SET_NULL, null=True, blank=True)
    prompt = models.TextField()
    negative_prompt = models.TextField(blank=True, null=True)
    status = models.CharField(max_length=20, default='pending')  # Example status field
    # Add other fields as needed

    def __str__(self):
        return f"Video generated by {self.user.username} - Status: {self.status}"
